[package]
name = "shinobu8-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
shinobu8-core = { path = "../shinobu8-core" }
clap = { version = "4.5.4", features = ["derive"] }
crossterm = "0.27.0"
ratatui = "0.26.3"
